---
- name: Check if docker is installed
  become: yes
  become_method: sudo
  command: which docker
  register: docker_check

- name: Install docker
  become: yes
  become_method: sudo
  when: docker_check.rc != 0
  yum:
    name: docker-ce
    state: present

- name: Start docker service
  become: yes
  become_method: sudo
  service:
    name: docker
    state: started
    enabled: yes
    
# Rewrite  everything below without using dnf, instead use role to update python

    - name: Dnf install 
      yum:
        name:
        - dnf
        state: present
    - name: Python install         
      dnf:
        name:
        - python3
        state: present
    - name: Docker clean
      yum:
        name:
        - docker
        - docker-client
        - docker-client-latest
        - docker-common
        - docker-latest
        - docker-latest-logrotate
        - docker-logrotate
        - docker-engine    
        state: absent
    - name: Docker-py clean    
      pip:
        name:
        - docker
        - docker-py
        executable: pip3
        state: absent
    - name: Add signing key
      ansible.builtin.rpm_key:
        key: "https://download.docker.com/linux/centos/gpg"
        state: present    
    - name: add docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
    - name: Install docker     
      yum:
        name:
        - docker-ce
        - docker-ce-cli
        - containerd.io    
        state: latest
    - name: Docker-py install       
      pip:
        name:
        - docker
        executable: pip3
        state: present
    - name: Make docker is started up
      service: name=docker state=started enabled=yes
